### ISSUE TITLE
Error: The `add-path` command is disabled.

### ISSUE THREAD

**Issue by 4x0v7** [wizhi/setup-task#3]
I have a Workflow file like this:

```yaml
name: tasks

on:
  push:
  pull_request:

env:
  TASKFILE_VERSION: 3.2.2

jobs:
  run-a-task:
    name: Run a task
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: wizhi/setup-task@v1
        with:
          version: ${{ env.TASKFILE_VERSION }}
      - name: Run a task
        run: task runme
```

When I push, I get the below error:

Run wizhi/setup-task@v1
  with:
    version: 3.2.2
  env:
    TASKFILE_VERSION: 3.2.2
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/15b43866-7cc0-41a7-88ae-192433c4923e -f /home/runner/work/_temp/ecbbe803-ab0f-40c7-ae57-95f5be287198
Error: Unable to process command '::add-path::/opt/hostedtoolcache/task/3.2.2/amd64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
